"""Generate frontend municipality centroids from the U.S. Census Gazetteer.

One-off setup tool (re-run when `COUNTIES` changes). NOT part of the scrape
pipeline. Pulls county-subdivision internal points (towns/villages/cities) for the
target counties from the Census 2024 Gazetteer and writes them as a baked JS module
the map imports — no runtime fetch, no hand-built coordinates.

Keyed by "County|Municipality" (DOR form) because municipality names repeat across
counties in the coverage area (e.g. "Cleveland, Town of" exists in two counties).

    python tools/fetch_centroids.py
"""

import urllib.request
from pathlib import Path

GAZETTEER_URL = (
    "https://www2.census.gov/geo/docs/maps-data/data/gazetteer/"
    "2024_Gazetteer/2024_gaz_cousubs_55.txt"  # 55 = Wisconsin
)

# WI county FIPS (GEOID chars 3-5) -> county name. Must match scraper/config.py
# COUNTIES and the DOR `county` field exactly.
COUNTY_FIPS = {
    "073": "Marathon",
    "069": "Lincoln",
    "067": "Langlade",
    "119": "Taylor",
    "115": "Shawano",
    "097": "Portage",
}

# Census subdivision type (last word of NAME) -> DOR municipality suffix.
DOR_TYPE = {"city": "City of", "village": "Village of", "town": "Town of"}

OUTPUT_PATH = Path(__file__).resolve().parent.parent / "frontend" / "src" / "lib" / "municipalities.js"


def fetch_rows() -> list[dict]:
    req = urllib.request.Request(GAZETTEER_URL, headers={"User-Agent": "wpr-property-transactions"})
    with urllib.request.urlopen(req, timeout=60) as resp:
        text = resp.read().decode("utf-8")
    lines = text.splitlines()
    header = [h.strip() for h in lines[0].split("\t")]
    return [dict(zip(header, [c.strip() for c in line.split("\t")])) for line in lines[1:] if line.strip()]


def build_centroids(rows: list[dict]) -> dict[str, list[float]]:
    out: dict[str, list[float]] = {}
    for r in rows:
        fips = r["GEOID"][2:5]
        county = COUNTY_FIPS.get(fips)
        if not county:
            continue
        name = r["NAME"]
        base, _, kind = name.rpartition(" ")
        suffix = DOR_TYPE.get(kind.lower())
        if not suffix:
            raise RuntimeError(f"Unexpected subdivision type in {name!r}")
        muni = f"{base}, {suffix}"
        out[f"{county}|{muni}"] = [round(float(r["INTPTLAT"]), 4), round(float(r["INTPTLONG"]), 4)]
    if not out:
        raise RuntimeError("No municipalities matched the target counties — check FIPS/URL.")
    return out


def region_view(centroids: dict[str, list[float]]) -> tuple[list[float], int]:
    lats = [c[0] for c in centroids.values()]
    lons = [c[1] for c in centroids.values()]
    center = [round((min(lats) + max(lats)) / 2, 4), round((min(lons) + max(lons)) / 2, 4)]
    return center, 8


def write_js(centroids: dict[str, list[float]], center: list[float], zoom: int) -> None:
    lines = [
        "// GENERATED by tools/fetch_centroids.py from the U.S. Census 2024 Gazetteer",
        "// (WI county subdivisions). Do not edit by hand — re-run the tool to refresh,",
        "// e.g. after changing the county set in scraper/config.py. Keyed by",
        '// "County|Municipality" (DOR form) because municipality names repeat across',
        '// counties in the coverage area (e.g. "Cleveland, Town of").',
        "export const MUNI_CENTROIDS = {",
    ]
    for key in sorted(centroids):
        lat, lon = centroids[key]
        lines.append(f'  {key!r}: [{lat}, {lon}],'.replace("'", '"'))
    lines.append("};")
    lines.append("")
    lines.append(f"export const REGION_CENTER = [{center[0]}, {center[1]}];")
    lines.append(f"export const REGION_ZOOM = {zoom};")
    lines.append("")
    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    rows = fetch_rows()
    centroids = build_centroids(rows)
    center, zoom = region_view(centroids)
    write_js(centroids, center, zoom)
    print(f"Wrote {len(centroids)} municipality centroids to {OUTPUT_PATH}")
    print(f"Region center {center}, zoom {zoom}")


if __name__ == "__main__":
    main()
